def scrub_input(v: str|bytes) -> bytes: ...
def b58encode_int(i: int, default_one: bool = True) -> bytes: ...
def b58encode(v: str|bytes) -> bytes: ...
def b58decode_int(v: str|bytes) -> int: ...
def b58decode(v: str|bytes) -> bytes: ...
def b58encode_check(v: str|bytes) -> bytes: ...
def b58decode_check(v: str|bytes) -> bytes: ...