def extract_prefix(bytes_: bytes) -> int: ...
def get_prefix(multicodec: str) -> bytes: ...
def add_prefix(multicodec: str, bytes_: bytes) -> bytes: ...
def remove_prefix(bytes_: str|bytes) -> bytes: ...
def get_codec(bytes_: str|bytes) -> str: ...
def is_codec(name: str) -> bool: ...